client_bundle:
  modes:
    build:
      bundles:
        client/vendor/scripts/kmalakoff-client-bundle.js:
          underscore: underscore
          backbone: backbone

          # libraries from https://github.com/kmalakoff
          backbone-articulation: backbone-articulation
          backbone-modelref: backbone-modelref
          background: background
          json-serialize: json-serialize
          knockback: knockback
          knockback-inspector: knockback-inspector
          lifecycle: lifecycle
          mixin-js: mixin-js
          underscore-awesomer: underscore-awesomer

postinstall:
  commands:
    # vendor libraries
    - 'cp -r vendor/scripts client/vendor/scripts'
    - 'cp -r vendor/styles client/vendor/styles'
    - 'cp -r vendor/img client/public/img'
