examples_lib:
  join: examples_lib
  bare: true
  output: ./build
  directories: [examples_lib]

tests:
  output: ./build
  directories:
    - ex_backbone_articulation_js
    - ex_background_js
    - ex_combined_examples
    - ex_mixin_js
    - ex_underscore_awesomer_js
  options:
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
    build:
      no_files_ok: ['test/packaging']

postinstall:
  copy_latest_underscore:
    command: 'cp'
    args: ['node_modules/underscore/underscore.js', 'vendor/underscore-latest.js']
  copy_latest_underscore_awesomer:
    command: 'cp'
    args: ['node_modules/underscore-awesomer/underscore-awesomer.js', 'vendor/underscore-awesomer-latest.js']
  copy_latest_backbone:
    command: 'cp'
    args: ['node_modules/backbone/backbone.js', 'vendor/backbone-latest.js']
  copy_latest_backbone_articulation:
    command: 'cp'
    args: ['node_modules/backbone-articulation/backbone-articulation.js', 'vendor/backbone-articulation-latest.js']
  copy_latest_background:
    command: 'cp'
    args: ['node_modules/background/background.js', 'vendor/background-latest.js']
  copy_latest_mixin:
    command: 'cp'
    args: ['node_modules/mixin-js/mixin-js.js', 'vendor/mixin-js-latest.js']
