examples_lib:
  output: build
  join: examples_lib
  bare: true
  directories: [examples_lib]

tests:
  output: build
  directories:
    - ex_backbone_articulation_js
    - ex_background_js
    - ex_mixin_js
    - ex_json_serialize_js
  options:
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      files:
        - '**/*.html'
    build:
      no_files_ok: [test/packaging]

postinstall:
  copy_latest_underscore:
    command: 'cp'
    args: ['underscore', 'vendor/underscore-latest.js']
  copy_latest_underscore_awesomer:
    command: 'cp'
    args: ['underscore-awesomer', 'vendor/underscore-awesomer-latest.js']
  copy_latest_backbone:
    command: 'cp'
    args: ['backbone', 'vendor/backbone-latest.js']
  copy_latest_backbone_articulation:
    command: 'cp'
    args: ['backbone-articulation', 'vendor/backbone-articulation-latest.js']
  copy_latest_json_serialize:
    command: 'cp'
    args: ['json-serialize', 'vendor/json-serialize-latest.js']
  copy_latest_lifecycle:
    command: 'cp'
    args: ['lifecycle', 'vendor/lifecycle-latest.js']
  copy_latest_backbone_relational:
    command: 'cp'
    args: ['backbone-articulation/vendor/backbone-relational-latest.js', 'vendor/backbone-relational-latest.js']
  copy_latest_background:
    command: 'cp'
    args: ['background', 'vendor/background-latest.js']
  copy_latest_mixin:
    command: 'cp'
    args: ['mixin-js', 'vendor/mixin-js-latest.js']
